spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/irep?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
logging:
  path: log/springboot
  file: log/SmartCiteCon.log
server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
thread-pool-factory:
  #IO密集型应用，线程数为2N+1
  corePoolSize: 1
  maxPoolSize: 1
  queueCapacity: 10000
  keepAliveSeconds: 120
test:
  location: internal_profile